// app/layout.jsx
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import Header from '../components/Header'

export const metadata = {
  title: 'My Application',
  description: 'Generated by Ritesh Pandit',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: ['dark', 'simple'] }}>
      <html lang="en">
        <body>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
