export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const USER_ENTRY_REQUEST = "USER_ENTRY_REQUEST"
export const USER_ENTRY_SUCCESS = "USER_ENTRY_SUCCESS"
export const USER_ENTRY_FAIL = "USER_ENTRY_FAIL"